apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-validator
  namespace: network-validation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-validator
subjects:
  - kind: ServiceAccount
    name: cluster-validator
    namespace: cluster-validator
