apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-validator-read
  namespace: openshift-console
rules:
  - apiGroups: [route.openshift.io]
    resources: [routes]
    resourceNames: [console]
    verbs: [get]
